services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: runner
    container_name: monterrey_crm_app
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - uploads_data:/app/public/uploads
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://${DB_USER}:${DB_PASSWORD}@mongodb:27017/monterrey_crm?authSource=admin
      - TZ=America/Santo_Domingo
    depends_on:
      - mongodb

  mongodb:
    image: mongo:7.0
    container_name: monterrey_mongodb
    restart: always
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=monterrey_crm
      - MONGO_INITDB_ROOT_USERNAME=${DB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASSWORD}

volumes:
  mongodb_data:
  uploads_data:
